### ISSUE TITLE
build error with 4.4 kernel

### ISSUE THREAD

**Issue by manfredsc** [groeck/k10temp#10]
The latest commit introduced a call to amd_smn_read(), which seems not to be existing on my
version 4.4 kernel. It would be great if you could support older kernels as well, again!

Thanks!
 
```
CC [M]  /home/user/Ryzen/k10temp-master/k10temp.o
/home/user/Ryzen/k10temp-master/k10temp.c: In function 'read_tempreg_nb_f17':
/home/user/Ryzen/k10temp-master/k10temp.c:142:2: error: implicit declaration of function 'amd_smn_read' [-Werror=implicit-function-declaration]
  amd_smn_read(amd_pci_dev_to_node_id(pdev),
  ^
cc1: some warnings being treated as errors
/usr/src/linux-4.4.104-39/scripts/Makefile.build:266: recipe for target '/home/user/Ryzen/k10temp-master/k10temp.o' failed

```

**Comment by groeck** [comment]
k10temp in 4.4 kernels does not and will never be able to correctly support all Threadripper variants and the associated server CPUs. I'll see what I can do to make it at least compile, but I would suggest to switch to more recent kernels instead.

**Comment by groeck** [comment]
This should now work, with the caveat mentioned above.
