### ISSUE TITLE
nct6775 driver problem ??

### ISSUE THREAD

**Issue by flip111** [groeck/k10temp#11]
Hello, sorry to hijack the issue list on this repo. However i couldn't find an e-mail address and the few repos listed here http://roeck-us.net/linux/drivers/ don't exist anymore. 

My fan control doesn't work and after talking to a few people on ##linux in freenode they suggested that it could be a driver issue. The original issue is posted [on launchpad](https://bugs.launchpad.net/ubuntu/+source/lm-sensors/+bug/1803795) and [github](https://github.com/lm-sensors/lm-sensors/issues/144)

From the sensors-detect log:
```
Found `Nuvoton NCT6792D Super IO Sensors'                   Success!
    (address 0x290, driver `nct6775')
```

`cat` is not able to read the driver `cat: /sys/class/hwmon/hwmon0/fan1_input: Invalid argument` (see log file in launchpad).

Fancontrol works on windows so i don't believe it's a hardware issue. More information about hardware in the same logfile on launchpad.

Please point me to somewhere else if this can't be discussed here.

**Comment by groeck** [comment]
Shotgun approach ?

Hmm, I guess I have to mark this driver private as well.
