### ISSUE TITLE
There is no Ryzen/Threadripper 1910/1900 (non X)

### ISSUE THREAD

**Issue by rigred** [groeck/k10temp#2]
Just a small notice
k10temp.c lists a Threadripper 1910.

As far as I am aware there exists no Threadripper 1910. Only the 1900X. 
```
	{ 0x17, "AMD Ryzen Threadripper 1920", 10000 },
	{ 0x17, "AMD Ryzen Threadripper 1910", 10000 },
};
```
Also see 
http://www.asrock.com/support/cpu.asp?s=TR4

https://www.gigabyte.com/Motherboard/X399-AORUS-Gaming-7-rev-10#support-cpu

Unless there is information that I am not aware of I think it's worth reviewing this list.
Currently no non-X 1900, 1910, 1920 or 1950 exists.

Do you have a source as to why these chips are included?
Am I missing something? Are these non-X OEM system parts?

**Comment by groeck** [comment]
Maybe the information I got was wrong. However, at least the 1920 was planned at some point; see http://www.cpu-world.com/news_2017/2017080901_AMD_is_readying_Ryzen_Threadripper_1920_CPU.html. Maybe the parts were planned but scrubbed. For now the entries don't hurt; we can revisit at a later time if they don't show up.

**Comment by rigred** [comment]
Ok thanks
I agree.
