### ISSUE TITLE
Ryzen 2400G Raven Ridge

### ISSUE THREAD

**Issue by Fulkerson** [groeck/k10temp#3]
The k10temp driver doesn't seem to work on the new raven ridge processors. Any news on this?

**Comment by groeck** [comment]
First I hear, and the information provided is not actionable.

**Comment by groeck** [comment]
Fixed.

**Comment by devurandom** [comment]
Fixed in 9be82d246958ee3049ca8eea7d0304217d6829f4?

Will this be in Linux 4.17? And will it be backported to 4.16? It applies cleanly to 4.16.6.

**Comment by groeck** [comment]
@devurandom: As the commit log suggests, 9be82d2 adds support for for Stoney Ridge and Bristol Ridge CPUs. Support for RavenRidge was added earlier, with "Synchronize with WIP upstream version". The question therefore is what you mean with "it" ?
Support for Raven Ridge ? See upstream commit 877d8948d0aa ("hwmon: (k10temp) Add support for AMD Ryzen w/ Vega graphics"). It may or may not find its way into v4.16.y.
Support for Stoney Ridge and Bristol Ridge ? See https://patchwork.kernel.org/patch/10370599/. I have Tested-by: feedback, but (unfortunately, as usual) no Reviewed-by:, meaning I (again) violate upstream guidelines if I send a pull request to Linus. I have not decided yet if I am going to risk risk his displeasure by doing that.

**Comment by devurandom** [comment]
Sorry, I mixed up the different processor names. I meant support for Raven Ridge. Looking at the code in 4.16.6, it appears that `PCI_DEVICE_ID_AMD_17H_RR_NB` was added in 4.16.6 (i.e. after 4.16.5), so it was already backported.
