### ISSUE TITLE
AMD A6-9220 Stoney Ridge

### ISSUE THREAD

**Issue by abucodonosor** [groeck/k10temp#4]
Hello,

it seems these APUs are not supported ?

I can provide dmesg and lscpi from such a box if needed.

Regards

**Comment by groeck** [comment]
We would need the output of "lspci -nn".

**Comment by groeck** [comment]
Updated driver. Please give it a try.

**Comment by groeck** [comment]
Can you test again with the latest code ? The code to read and report the critical temperature values was wrong (I think).

**Comment by abucodonosor** [comment]
looks like is the same code you posted on LKML .. anyway re-tested here too
all looks OK.

```
k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +27.9 C  (high = +70.0 C)
                       (crit = +100.0 C, hyst = +99.0 C)

```
