### ISSUE TITLE
On dual socket EPYC system temp seems to match ony first CPU?

### ISSUE THREAD

**Issue by abucodonosor** [groeck/k10temp#5]
Hello,

I have an dual socket system with 2 * EPYC 7281 CPUs.

Compared to IPMI output it seems the k10temp temps
matches only the first CPU temps ?

```
crazy@ant:~/Work/Linux$ sensors
k10temp-pci-00e3
Adapter: PCI adapter
temp1:        +24.5°C  (high = +70.0°C)

k10temp-pci-00d3
Adapter: PCI adapter
temp1:        +24.5°C  (high = +70.0°C)

k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +24.5°C  (high = +70.0°C)

k10temp-pci-00fb
Adapter: PCI adapter
temp1:        +24.5°C  (high = +70.0°C)

k10temp-pci-00eb
Adapter: PCI adapter
temp1:        +24.5°C  (high = +70.0°C)

k10temp-pci-00db
Adapter: PCI adapter
temp1:        +24.5°C  (high = +70.0°C)

k10temp-pci-00cb
Adapter: PCI adapter
temp1:        +24.5°C  (high = +70.0°C)

k10temp-pci-00f3
Adapter: PCI adapter
temp1:        +24.5°C  (high = +70.0°C)

```

Now here what IPMI sensors reports for the CPUs:

```
crazy@ant:~/Work/Linux$ sudo ipmi-sensors  --ignore-unrecognized-events --ignore-not-available-sensors --output-sensor-thresholds
ID   | Name            | Type              | Reading    | Units | Lower NR   | Lower C    | Lower NC   | Upper NC   | Upper C    | Upper NR   | Event
4    | CPU1 Temp       | Temperature       | 24.00      | C     | 5.00       | 5.00       | 10.00      | 95.00      | 100.00     | 100.00     | 'OK'
71   | CPU2 Temp       | Temperature       | 22.00      | C     | 5.00       | 5.00       | 10.00      | 95.00      | 100.00     | 100.00     | 'OK'

```

lspci -nn output of the box:
http://ftp.frugalware.org/pub/other/people/crazy/ant.lspci

Regards

**Comment by groeck** [comment]
That is where the lack of non-NDA documentation hurts us. Problem is that the temperatures are all pulled from the first instance of 1022:1450, which is wrong (and there should really be just one temperature displayed). Can you attach the output of "lspci -t -v" ?

**Comment by groeck** [comment]
Can you try the code in the 'testing' branch ? I have no idea if it helps, but it is necessary anyway to avoid race conditions, and we might be lucky.

**Comment by abucodonosor** [comment]
@groeck 

I can test any kind patches ( debug patches ) .. whatever is needed for you to get more data.
Just let me know.

**Comment by groeck** [comment]
Interesting. That suggests that the output is really available per CPU core cluster, not only per CPU. Thanks for testing!.

**Comment by abucodonosor** [comment]
@groeck 

I've tested your 2 patches from LKML on top 4.16.5

x86/amd_nb: Add support for Raven Ridge CPUs
hwmon: (k10temp) Use API function to access System Management Network
( this one need won't apply but is easy to adjust to 4.16.5 code )

Also TMPs on my box looks fine now. At least no more 'just one value'
and they change based on what cores I poke.

If you want me to add a Tested-by on LKML let me know.

**Comment by groeck** [comment]
@abucodonosor: Tested-by: would be great; it might help getting approval from the x86 maintainers. For the patches to apply cleanly, you would probably need to apply the patches queued for v4.16.6 as well as https://patchwork.kernel.org/patch/10367393/.

**Comment by groeck** [comment]
Thanks!
