### ISSUE TITLE
cannot build on Kernel 4.15+

### ISSUE THREAD

**Issue by Saentist** [groeck/k10temp#8]
```
/opt/k10temp# make
make[2]: *** No rule to make target 'tools/objtool/objtool', needed by '/opt/k10temp/k10temp.o'.  Stop.
Makefile:1552: recipe for target '_module_/opt/k10temp' failed
make[1]: *** [_module_/opt/k10temp] Error 2
Makefile:50: recipe for target 'modules' failed
make: *** [modules] Error 2
```
objtool is build in kernel not a external tool as i read from kernel 4.15

**Comment by groeck** [comment]
That is not a k10temp problem. It is a distribution problem. The distribution should provide objtool as part of the kernel image or headers, but it doesn't. Nothing we can do about it from the driver side.
